"""first_migration

Revision ID: 5039bd4c0a70
Revises: 
Create Date: 2021-03-18 12:49:14.991961

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5039bd4c0a70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('job', sa.String(), nullable=True),
                    sa.Column('company', sa.String(), nullable=True),
                    sa.Column('ssn', sa.String(), nullable=True),
                    sa.Column('residence', sa.String(), nullable=True),
                    sa.Column('blood_group', sa.String(), nullable=True),
                    sa.Column('website', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('sex', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('birthdate', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
