version: "3.4"

services:
  db:
    image: postgres:13.2
    env_file:
      - .env
    ports:
      - "5432:5432"
  python_db:
    build: .
#    command: python connect.py
    env_file:
      - .env
    volumes:
      - ./app:/app
#    ports:
#      - "8000:8000"
    depends_on:
      - db
